let obj= [{
    specific:"n1",
    off: "50%",
    img:"watch.png",
    name:"Rolex Brown rager (men's watch)",
    strike:"10,000",
    mrp :5000,
    save:"5,000",
    color:"brown",
    id:"cart1",
   
},{
    specific:"n2",
    off: "25%",
    img:"apple.png",
    name:"Apple MagicBoard(apple's product)",
    strike:"20,000",
    mrp:15000,
    save:"5,000",
    color:"Aliceblue",
    id:"cart2",
  
},{
    specific:"n3",
    off: "15%",
    img:"iphone.png",
    name:"Iphone 13 pro max(apple's product)",
    strike:"1,29,399",
    mrp:99000,
    save:"30,399",
    color:"white",
    id:"cart3",
    
},{
    specific:"n4",
    off: "50%",
    img:"earpod.png",
    name:"BoAt earpod 2(BoAt's product)",
    strike:"6,000",
    mrp:3000,
    save:"3,000",
    color:"pure White",
    id:"cart4",
   
},{
    specific:"n5",
    off: "25%",
    img:"headphone.png",
    name:"Sony headphone t2(Sony product)",
    strike:"20,000",
    mrp:15000,
    save:"5,000",
    color:"black",
    id:"cart5",
  
},{
    specific:"n6",
    off: "25%",
    img:"wire.png",
    name:"Nikon 100px camera (Wild camera)",
    strike:"40,000",
    mrp:30000,
    save:"10,000",
    color:"black",
    id:"cart6",
    
},{
    specific:"n7",
    off: "40%",
    img:"mack.png",
    name:"Apple mac(Apple's modern product)",
    strike:"3,29,399",
    mrp:200000,
    save:"1,29,399",
    color:"white",
    id:"cart7",
  
},{
    specific:"n8",
    off: "25%%",
    img:"laptop.png",
    name:"acer laptop s20(acer's laptop)",
    strike:"60,000",
    mrp:50000,
    save:"10,000",
    color:"grey",
    id:"cart8",

},{
    specific:"n9",
    off: "50%",
    img:"cricket.png",
    name:"Kookambura firered(English Willow)",
    strike:10000,
    mrp:"5,000",
    save:"5,000",
    color:"white",
    id:"cart9",
   
},{
    specific:"n10",
    off: "25%",
    img:"formal.png",
    name:"Rixer formal shoe(Men's shoe)",
    strike:"2,000",
    mrp:1500,
    save:"500",
    color:"Royal Black",
    id:"cart10",
 
},{
    specific:"n11",
    off: "60%",
    img:"formal-2.png",
    name:"texa formal shoe(Men's shoe)",
    strike:"2,500",
    mrp:1000,
    save:"5,000",
    color:"British Brown",
    id:"cart11",
    
},{ specific:"n12",
    off: "40%",
img:"informal.png",
name:"Nike classic red (Men's sport shoe)",
strike:"3,000",
mrp:1500,
save:"1,500",
color:"Red",
id:"cart12",
},
{
    specific:"n13",
    off: "25%",
    img:"coat.png",
    name:"Black coat and pant (Men's coat)",
    strike:"20,000",
    mrp:10000,
    save:"10,000",
    color:"Royal black",
    id:"cart13",
 
},{
    specific:"n14",
    off: "50%",
    img:"red.png",
    name:"pink shirt(Men's wear)",
    strike:"5,000",
    mrp:2500,
    save:"2,500",
    color:"red",
    id:"cart14",

},{  specific:"n15",
    off: "25%",
    img:"shirt.png",
    name:"formal red striped shirt(Men's formal)",
    strike:"20,000",
    mrp:15000,
    save:"5,000",
    color:"red striped shirt",
    id:"cart15",
  },
    {
        specific:"n16",
        off: "50%",
    img:"blue.png",
    name:"Formal blue striped shirt(Men's formal)",
    strike:"4,500",
    mrp:2500,
    save:"2,000",
    color:"blue striped shirt",
    id:"cart16",
   
    },{specific:"n17",
        off: "20%",
    img:"watch-2.png",
    name:"Moto smart watch 5(Men's wear)",
    strike:"10,000",
    mrp:9000,
    save:"1,00",
    color:"black",
    id:"cart17",
    
    },{
        specific:"n18",
        off: "50%",
    img:"Women-WATCH.png",
    name:"Rolex Brown rager (men's watch)",
    strike:"8,000",
    mrp:4000,
    save:"2,000",
    color:"Pure grey",
    id:"cart18",

    },{
        specific:"n19",
        off: "50%",
    img:"india.png",
    name:"Virat signed Jersey(Orginal India jersey)",
    strike:"10,000",
    mrp:5000,
    save:"5,000",
    color:"Blue",
    id:"cart19",
  
    },{
        specific:"n20",
        off: "50%",
    img:"csk.png",
    name:"Chennai super kings Jersey(Official jersey)",
    strike:"1,000",
    mrp:500,
    save:"5,000",
    color:"Yellow",
    id:"cart20",

    },{
        specific:"n21",
        off: "50%",
    img:"gym.webp",
    name:"The flexbench(gym equipment)",
    strike:"30,000",
    mrp:15000,
    save:"15,000",
    color:"black",
    id:"cart21",

    },{
        specific:"n22",
        off: "50%",
    img:"hoodie.jpg",
    name:"Kids T-shirt",
    strike:"1,000",
    mrp:500,
    save:"500",
    color:"white",
    id:"cart22",
   
    },{
        specific:"n23",
        off: "50%",
    img:"pickachu.jpg",
    name:"Pickachu bag(kids bag)",
    strike:"499",
    mrp:169,
    save:"330",
    color:"Yellow",
    id:"cart23",
   
    },
    {
        specific:"n24",
        off: "50%",
        img:"hero.jpg",
        name:"Hero pen(neat and good handwriting)",
        strike:"300",
        mrp:150,
        save:"150",
        color:"Green,Brown,Black", 
        id:"cart24"  ,
   
    }]